// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model
//
//import (
//	"time"
//)
//
//type Comment struct {
//	ID            string         `json:"id"`
//	User          *User          `json:"user"`
//	Content       string         `json:"content"`
//	LikeCount     int            `json:"likeCount"`
//	ReplyCount    int            `json:"replyCount"`
//	ParentPost    *Post          `json:"parentPost,omitempty"`
//	ParentComment *Comment       `json:"parentComment,omitempty"`
//	Likes         []*CommentLike `json:"likes,omitempty"`
//	Comments      []*Comment     `json:"comments,omitempty"`
//	Liked         *bool          `json:"liked,omitempty"`
//	CreatedAt     time.Time      `json:"createdAt"`
//}
//
//type CommentLike struct {
//	CommentID string `json:"commentId"`
//	User      *User  `json:"user"`
//}
//
//type Friend struct {
//	Sender   *User `json:"sender"`
//	Receiver *User `json:"receiver"`
//	Accepted bool  `json:"accepted"`
//}
//
//type FriendInput struct {
//	Sender   string `json:"sender"`
//	Receiver string `json:"receiver"`
//}
//
//type NewComment struct {
//	Content       string  `json:"content"`
//	ParentPost    *string `json:"parentPost,omitempty"`
//	ParentComment *string `json:"parentComment,omitempty"`
//}
//
//type NewPost struct {
//	Content string    `json:"content"`
//	Privacy string    `json:"privacy"`
//	Files   []*string `json:"files,omitempty"`
//}
//
//type NewUser struct {
//	FirstName string    `json:"firstName"`
//	LastName  string    `json:"lastName"`
//	Username  string    `json:"username"`
//	Email     string    `json:"email"`
//	Password  string    `json:"password"`
//	Dob       time.Time `json:"dob"`
//	Gender    string    `json:"gender"`
//}
//
//type Pagination struct {
//	Start int `json:"start"`
//	Limit int `json:"limit"`
//}
//
//type Post struct {
//	ID           string      `json:"id"`
//	User         *User       `json:"user"`
//	Content      string      `json:"content"`
//	Privacy      string      `json:"privacy"`
//	LikeCount    int         `json:"likeCount"`
//	CommentCount int         `json:"commentCount"`
//	ShareCount   int         `json:"shareCount"`
//	Files        []*string   `json:"files,omitempty"`
//	Likes        []*PostLike `json:"likes,omitempty"`
//	Comments     []*Comment  `json:"comments,omitempty"`
//	Liked        *bool       `json:"liked,omitempty"`
//	CreatedAt    time.Time   `json:"createdAt"`
//}
//
//type PostLike struct {
//	PostID string `json:"postId"`
//	User   *User  `json:"user"`
//}
//
//type UpdateUser struct {
//	FirstName string `json:"firstName"`
//	LastName  string `json:"lastName"`
//	Password  string `json:"password"`
//	Gender    string `json:"gender"`
//}
//
//type User struct {
//	ID          string    `json:"id"`
//	FirstName   string    `json:"firstName"`
//	LastName    string    `json:"lastName"`
//	Username    string    `json:"username"`
//	Email       string    `json:"email"`
//	Dob         time.Time `json:"dob"`
//	Gender      string    `json:"gender"`
//	Active      bool      `json:"active"`
//	Profile     *string   `json:"profile,omitempty"`
//	Background  *string   `json:"background,omitempty"`
//	CreatedAt   time.Time `json:"createdAt"`
//	Posts       []*Post   `json:"posts,omitempty"`
//	FriendCount int       `json:"friendCount"`
//	Friended    string    `json:"friended"`
//}
