package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/yahkerobertkertasnya/TPAWebBack/graph/model"
)

// CreateNotification is the resolver for the createNotification field.
func (r *mutationResolver) CreateNotification(ctx context.Context, notification model.NewNotification) (*model.Notification, error) {
	var blocked *model.BlockNotification
	userID := ctx.Value("UserID").(string)

	if err := r.DB.First(&blocked, "sender_id = ? AND receiver_id = ?", userID, notification.UserID).Error; err == nil && blocked != nil {
		return nil, nil
	}

	newNotification := &model.Notification{
		ID:        uuid.NewString(),
		Message:   notification.Message,
		UserID:    notification.UserID,
		SenderID:  userID,
		Seen:      false,
		PostID:    notification.PostID,
		ReelID:    notification.ReelID,
		StoryID:   notification.StoryID,
		GroupID:   notification.GroupID,
		CreatedAt: time.Now(),
	}

	if err := r.DB.Save(&newNotification).Error; err != nil {
		fmt.Println(err)
		return nil, err
	}

	r.Redis.Del(ctx, fmt.Sprintf("notifications:%s:user", notification.UserID))

	return newNotification, nil
}

// GetUnreadNotifications is the resolver for the getUnreadNotifications field.
func (r *mutationResolver) GetUnreadNotifications(ctx context.Context) ([]*model.Notification, error) {
	var notifications []*model.Notification
	userID := ctx.Value("UserID").(string)

	if err := r.DB.
		Order("created_at DESC").
		Preload("Sender").
		Find(&notifications, "user_id = ? AND seen = false", userID).Error; err != nil {
		return nil, err
	}

	go func() {
		for _, notification := range notifications {

			notification.Seen = true
			if err := r.DB.Save(&notification).Error; err != nil {
				continue
			}
		}
	}()

	return notifications, nil
}

// BlockUser is the resolver for the blockUser field.
func (r *mutationResolver) BlockUser(ctx context.Context, username string) (*model.BlockNotification, error) {
	var user *model.User
	userID := ctx.Value("UserID").(string)

	if err := r.DB.First(&user, "username = ?", username).Error; err != nil {
		return nil, err
	}

	if serializedUser, err := r.Redis.Get(ctx, fmt.Sprintf(`user:%s`, user.ID)).Result(); err != nil {

		if serializedUser, err := json.Marshal(user); err != nil {
			return nil, err
		} else {
			r.Redis.Set(ctx, fmt.Sprintf(`user:%s`, username), serializedUser, 10*60*time.Minute)
		}

	} else {
		if err := json.Unmarshal([]byte(serializedUser), &user); err != nil {
			return nil, err
		}
	}

	var blockNotif *model.BlockNotification

	if err := r.DB.First(&blockNotif, "sender_id = ? AND receiver_id = ?", user.ID, userID).Error; err == nil && blockNotif != nil {

		if err := r.DB.Delete(&blockNotif).Error; err != nil {
			return nil, err
		}

		r.Redis.Del(ctx, fmt.Sprintf("user:%s:blocked:%s", userID, user.ID))
		return blockNotif, nil
	}

	blockNotif = &model.BlockNotification{
		SenderID:   user.ID,
		ReceiverID: userID,
	}

	if err := r.DB.Save(&blockNotif).Error; err != nil {
		return nil, err
	}

	r.Redis.Del(ctx, fmt.Sprintf("user:%s:blocked:%s", userID, user.ID))

	return blockNotif, nil
}

// GetNotifications is the resolver for the getNotifications field.
func (r *queryResolver) GetNotifications(ctx context.Context) ([]*model.Notification, error) {
	var notifications []*model.Notification
	userID := ctx.Value("UserID").(string)

	if notificationsSerialized, err := r.Redis.Get(ctx, fmt.Sprintf("notifications:%s:user", userID)).Result(); err != nil {
		if err := r.DB.
			Order("created_at DESC").
			Preload("Sender").
			Find(&notifications, "user_id = ?", userID).Error; err != nil {
			return nil, err
		}

		if notificationsSerialized, err := json.Marshal(notifications); err != nil {
			return nil, err
		} else {
			r.Redis.Set(ctx, fmt.Sprintf("notifications:%s:user", userID), notificationsSerialized, 10*time.Minute)
		}
	} else {
		if err := json.Unmarshal([]byte(notificationsSerialized), &notifications); err != nil {
			return nil, err
		}
	}

	return notifications, nil
}
